version: "3.3"
services:
  todo-service:
    build:
      context: ./todo-service
      dockerfile: ../Dockerfile
    restart: on-failure
    command: ["python", "index.py", "3000"]
    env_file:
      - .env
    ports:
     - "3000:3000"
    volumes:
     - ./todo-service:/app
    depends_on:
    - eureka

  user-service:
    build:
      context: ./user-service
      dockerfile: ../Dockerfile
    restart: on-failure
    command: ["python", "index.py", "5000"]
    env_file:
      - .env
    ports:
     - "5000:5000"
    volumes:
     - ./user-service:/app
    depends_on:
    - eureka

  eureka:
    image: springcloud/eureka
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - eureka
